apiVersion: deployments.plural.sh/v1alpha1
kind: Pipeline
metadata:
  name: gle-demo-vpa
spec:
  projectRef:
    name: gle-demo
  stages:
    - name: dev
      services:
        - serviceRef:
            name: vpa-dev
            namespace: gle-demo
          criteria:
            prAutomationRef:
              name: gle-demo-pra
    - name: prod
      services:
        - serviceRef:
            name: vpa-prod
            namespace: gle-demo
          criteria:
            prAutomationRef:
              name: gle-demo-pra
  edges:
    - from: dev
      to: prod
      gates:
      - name: approval-gate
        type: APPROVAL