apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: kube-state-metrics-dev
spec:
  name: kube-state-metrics
  namespace: kube-state-metrics
  helm:
    chart: kube-state-metrics
    version: 5.19.0 # VERSION
    url: https://prometheus-community.github.io/helm-charts
  clusterRef:
    kind: Cluster
    name: alexdaviddev
    namespace: alexdavid
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: kube-state-metrics-dev-alexdavid
spec:
  cascade:
    delete: true
  serviceRef:
    name: kube-state-metrics-dev
    namespace: alexdavid
  projectRef:
    name: alexdavid
  tags:
    tier: dev