apiVersion: deployments.plural.sh/v1alpha1
kind: Pipeline
metadata:
  name: test-fleet-vpa
spec:
  projectRef:
    name: test-fleet
  stages:
    - name: dev
      services:
        - serviceRef:
            name: vpa-dev
            namespace: test-fleet
          criteria:
            prAutomationRef:
              name: test-fleet-pra
    - name: prod
      services:
        - serviceRef:
            name: vpa-prod
            namespace: test-fleet
          criteria:
            prAutomationRef:
              name: test-fleet-pra
  edges:
    - from: dev
      to: prod
      gates:
      - name: approval-gate
        type: APPROVAL