apiVersion: deployments.plural.sh/v1alpha1
kind: Pipeline
metadata:
  name: cvent-vpa
spec:
  projectRef:
    name: cvent
  stages:
    - name: dev
      services:
        - serviceRef:
            name: vpa-dev
            namespace: cvent
          criteria:
            prAutomationRef:
              name: cvent-pra
    - name: prod
      services:
        - serviceRef:
            name: vpa-prod
            namespace: cvent
          criteria:
            prAutomationRef:
              name: cvent-pra
  edges:
    - from: dev
      to: prod
      gates:
      - name: approval-gate
        type: APPROVAL