apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: vpa-prod
spec:
  name: vpa
  namespace: vpa
  helm:
    chart: vpa
    version: 4.4.5 # VERSION
    url: https://charts.fairwinds.com/stable
    values:
      admissionController:
        enabled: false
  clusterRef:
    kind: Cluster
    name: gke-demo-prodw
    namespace: gke-demo2
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: vpa-prod-gke-demo2
spec:
  cascade:
    delete: true
  serviceRef:
    name: vpa-prod
    namespace: gke-demo2
  projectRef:
    name: gke-demo2
  tags:
    tier: prod