apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: kube-state-metrics-dev
spec:
  name: kube-state-metrics
  namespace: kube-state-metrics
  helm:
    chart: kube-state-metrics
    version: 5.19.0 # VERSION
    url: https://prometheus-community.github.io/helm-charts
  clusterRef:
    kind: Cluster
    name: gkedemo1dev
    namespace: gkedem01
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: kube-state-metrics-dev-gkedem01
spec:
  cascade:
    delete: true
  serviceRef:
    name: kube-state-metrics-dev
    namespace: gkedem01
  projectRef:
    name: gkedem01
  tags:
    tier: dev